name: DRF Unit Tests
on:
  push:
    branches:
      - main
jobs:
  test:

    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache dependency 
        uses: actions/cache@v2 
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Setup python environment 
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' 
      - name: Install requirements 
        run: pip install -r requirements.txt

      - name: Uninstall requirement
        run: pip uninstall -y setuptools
      - name: Install requirement
        run: pip install setuptools
      - name: Update
        run: python3 -m pip install --upgrade pip setuptools wheel

      - name: Run Migrations 
        run: python manage.py migrate --run-syncdb
      - name: Run Test 
        run: python manage.py test